openapi: 3.0.3
info:
  title: SpaceMarine specification
  version: 1.0.11
servers:
  - url: http://spacemarine2.swagger.io/starship
tags:
  - name: SpaceMarine
    description: default operations with collection of SpaceMarine in Second WebService
paths:
  /create/{id}/{name}:
    post:
      tags:
        - SpaceMarine
      summary: Create Landing craft by ID.
      description: Create Landing craft by ID.
      operationId: deleteSpaceMarineById
      parameters:
        - name: id
          in: path
          description: Landing craft ID
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: name
          in: path
          description: Landing craft name
          required: true
          schema:
            type: string
            minimum: 1
      responses:
          '200':
            description: Successful operation
            content:
              application/xml:
                schema:
                  $ref: '#/components/schemas/SpaceCraft'
          '400':
            description: Invalid ID or Name supplied
  /{starship-id}/unload-all:
    post:
      tags:
        - SpaceMarine
      summary: Disembark all paratroopers from SpaceCraft by ID.
      description: Disembark all paratroopers from SpaceCraft by ID.
      operationId: disembarkAllParatroopers
      parameters:
        - name: starship-id
          in: path
          description: Landing craft ID
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
          '200':
            description: Successful operation
            content:
              application/xml:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/SpaceMarine'
                  xml:
                    name: 'SpaceMarine'
          '400':
            description: Invalid ID supplied
components:
  schemas:
    SpaceCraft:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1234567
          minimum: 1
          nullable: false
        name:
          type: string
          example: 'Name'
          minLength: 1
          nullable: false
        SpaceMarine:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/SpaceMarine'
    SpaceMarine:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1234567
          minimum: 1
          nullable: false
        name:
          type: string
          example: 'Name'
          minLength: 1
          nullable: false
        cooridinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          example: '2021-03-23T16:43:32.010069453'
          format: date-time
          nullable: false
        health:
          type: integer
          format: int64
          example: 200
          minimum: 1
        height:
          type: number
          example: 34.23
        weaponType:
          $ref: '#/components/schemas/WeaponType'
        meleeWeapon:
          $ref: '#/components/schemas/MeleeWeapon'
        chapter:
          $ref: '#/components/schemas/Chapter'
    Coordinates:
      type: object
      properties:
        x:
          type: number
          example: 1.2
          maximum: 286
        y:
          type: number
          example: 1.3
          minimum: -685
          nullable: false
    WeaponType:
      type: string
      nullable: true
      enum: 
        - BOLTGUN
        - COMBI_PLASMA_GUN
        - GRAV_GUN
    MeleeWeapon:
      type: string
      nullable: true
      enum: 
        - POWER_SWORD
        - CHAIN_AXE
        - MANREAPER
        - POWER_BLADE
    Chapter:
      type: object
      nullable: false
      properties:
        name:
          type: string
          example: 'Name'
          nullable: false
          minLength: 1
        world:
          type: string
          example: 'World'
          nullable: true
